import {ItemModel} from "../../app/models/item.model";

export const itemDummydata: ItemModel[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality over-ear Bluetooth headphones with noise-cancellation.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 199.99,
    in_stock: true,
    stock_num: 150,
    category: ['Audio', 'Gaming'],
  },
  {
    id: '2',
    name: 'Ergonomic Office Chair',
    description: 'Comfortable office chair with lumbar support and adjustable height.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 149.99,
    in_stock: true,
    stock_num: 45,
    category: ['Büro'],
  },
  {
    id: '3',
    name: '4K Action Camera',
    description: 'Waterproof action camera with 4K resolution and wide-angle lens.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 249.99,
    in_stock: false,
    stock_num: 0,
    category: ['Foto', 'Video', 'Drohnen'],
  },
  {
    id: '4',
    name: 'Gaming Laptop',
    description: 'High-performance laptop with NVIDIA graphics and Intel i7 processor.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 1299.99,
    in_stock: true,
    stock_num: 20,
    category: ['Notebooks', 'Gaming', 'PC'],
  },
  {
    id: '5',
    name: 'Smartphone with 5G',
    description: 'Latest generation smartphone with 5G connectivity and OLED display.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 799.99,
    in_stock: true,
    stock_num: 75,
    category: ['Handys'],
  },
  {
    id: '6',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit mechanical keyboard with customizable keys.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 99.99,
    in_stock: true,
    stock_num: 100,
    category: ['Gaming', 'PC'],
  },
  {
    id: '7',
    name: '4K Ultra HD TV',
    description: '55-inch Smart TV with 4K resolution and HDR support.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 699.99,
    in_stock: false,
    stock_num: 0,
    category: ['TV'],
  },
  {
    id: '8',
    name: 'Wi-Fi 6 Router',
    description: 'High-speed router with Wi-Fi 6 support for faster internet connectivity.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 129.99,
    in_stock: true,
    stock_num: 60,
    category: ['Netzwerk'],
  },
  {
    id: '9',
    name: 'Drone with 4K Camera',
    description: 'Advanced drone with 4K camera and GPS for precise flying.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 499.99,
    in_stock: true,
    stock_num: 35,
    category: ['Drohnen', 'Foto', 'Video'],
  },
  {
    id: '10',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof portable speaker with deep bass and long battery life.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 59.99,
    in_stock: true,
    stock_num: 200,
    category: ['Audio'],
  },
  {
    id: '11',
    name: 'Noise-Cancelling Earbuds',
    description: 'Compact wireless earbuds with active noise-cancelling technology.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 149.99,
    in_stock: true,
    stock_num: 85,
    category: ['Audio'],
  },
  {
    id: '12',
    name: 'Curved Gaming Monitor',
    description: '34-inch curved monitor with 144Hz refresh rate and 1ms response time.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 499.99,
    in_stock: true,
    stock_num: 25,
    category: ['Gaming', 'PC'],
  },
  {
    id: '13',
    name: 'Smart Home Security Camera',
    description: 'Wireless security camera with motion detection and night vision.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 89.99,
    in_stock: true,
    stock_num: 130,
    category: ['Netzwerk'],
  },
  {
    id: '14',
    name: '2-in-1 Laptop/Tablet',
    description: 'Convertible laptop with touch screen and detachable keyboard.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 899.99,
    in_stock: true,
    stock_num: 40,
    category: ['Notebooks'],
  },
  {
    id: '15',
    name: 'Professional DSLR Camera',
    description: 'Full-frame DSLR camera with 24MP sensor and 4K video recording.',
    picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBCowy5A4eNzFEhgMS-Rd0897WC3Pq7JSNw&s',
    price: 1999.99,
    in_stock: false,
    stock_num: 0,
    category: ['Foto', 'Video'],
  },
];
